### ISSUE TITLE
Provider only accepts a single child

### ISSUE THREAD

**Issue by TimoStaudinger** [camwest/react-slot-fill#24]
Currently, the `Provider` component [accepts only a single child](https://github.com/camwest/react-slot-fill/blob/f4087870aa3f74b86cb55f882e9f398586800256/src/lib/components/Provider.ts#L38):

```
render() {
  return React.Children.only(this.props.children);
}
```

This somewhat messes with our implementation, and also seems to render the example in the readme invalid:

```
import Toolbar from './Toolbar';
import Feature from './Feature';

import { Provider } from 'react-slot-fill';

const App = () =>
  <Provider>
    <Toolbar />
    <Feature />
  </Provider>

ReactDOMFiber.render(
  <App />,
  document.getElementById('root')
);
```

---

Did I misunderstand any of this? Is there a reason why the library would not allow multiple children for `Provider`?

**Comment by camwest** [comment]
The Provider currently doesn’t render any html elements so it conforms to the React 15.x API where it creates a context and then renders the provided child inside that context.

The docs are out of date.

We can update to React 16.x only and change this so that Provider can handle multiple children. Want to make the change?

**Comment by TimoStaudinger** [comment]
Yep, I'll try to find some time this week to submit a PR for this.

From our perspective, depending on React 16 is fine, as we are already on 16 anyhow.

**Comment by camwest** [comment]
Ok awesome!
