### ISSUE TITLE
error TS2554: Expected 1-2 arguments, but got 0

### ISSUE THREAD

**Issue by MMRandy** [camwest/react-slot-fill#34]
I am getting this error after cloning the project and running npm i and npm start.  Seems like a dependency issue...what am I missing? 

```
Failed to compile.

./src/lib/components/Provider.ts
(20,5): error TS2554: Expected 1-2 arguments, but got 0.
```

**Comment by camwest** [comment]
I think the React type definitions updated. It looks like  super(); in Provider.ts should be passing props but it's not. Try using yarn to get the exact same set of dependencies instead of npm and you should be good to go. Feel free to submit a PR to update the yarn.lock and address the super() issue.
